FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV API_URL=http://rna_api:8000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --chown=nextjs:nodejs .next/standalone /app
COPY --chown=nextjs:nodejs .next/static /.next/static
COPY --chown=nextjs:nodejs public /app/public

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
